version: "3.9"

services:
  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build:
      context: .
      target: dev
      args:
        MIX_ENV: dev
    command: mix phx.server
    env_file: .env
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - .:/opt/app

volumes:
  deps:
  pg_data:
